name: Phil Evans Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8eaddd'
    - '#000001'
    - '#3a5b86'
    - '#ede3d9'
    - '#7b5a38'
  brandStrength: 0.75
  lightness: 0.36164379701949656
  saturation: 0.6875
  rhythmicContrast: 0.9367107467260212
purpose: []
